version: "3"

services:
#  flyway:
#    image: flyway/flyway:latest
#    command: -url=jdbc:mysql://db/mobile_app_ws?allowPublicKeyRetrieval=true&useSSL=false -schemas=mobile_app_ws -user=root -password=P@ssw0rd -connectRetries=60 migrate
#    volumes:
#      - ./src/main/resources/db/migration:/flyway/sql
#    depends_on:
#      - db
#    networks:
#      - backend

  db:
    image: mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=authservice
      - MYSQL_PASSWORD=P@ssw0rd
      - MYSQL_USER=myuser
    ports:
      - "3306:3306"
    volumes:
      - authservice:/var/lib/mysql
    networks:
      - backend

volumes:
  authservice:
    driver: local

networks:
  backend: